package com.caoxx.utils;

import java.math.BigDecimal;
import java.util.Date;

public class UserContract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.USER_NO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String userNo;
    
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.CONTRACT_NO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.OPEN_CHARGE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private BigDecimal openCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.CLOSE_CURR_CHARGE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private BigDecimal closeCurrCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.CLOSE_LAST_CHARGE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private BigDecimal closeLastCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.MARGIN
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private BigDecimal margin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.CONTRACT_UNIT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Integer contractUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.TICK_SIZE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private BigDecimal tickSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.OPEN_CHARGE_RATE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private BigDecimal openChargeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_CONTRACT.CLOSE_CURR_CHARGE_RATE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    private BigDecimal closeCurrChargeRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.ID
     *
     * @return the value of T_USER_CONTRACT.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.ID
     *
     * @param id the value for T_USER_CONTRACT.ID
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.USER_NO
     *
     * @return the value of T_USER_CONTRACT.USER_NO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.USER_NO
     *
     * @param userNo the value for T_USER_CONTRACT.USER_NO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.CONTRACT_NO
     *
     * @return the value of T_USER_CONTRACT.CONTRACT_NO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.CONTRACT_NO
     *
     * @param contractNo the value for T_USER_CONTRACT.CONTRACT_NO
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.OPEN_CHARGE
     *
     * @return the value of T_USER_CONTRACT.OPEN_CHARGE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public BigDecimal getOpenCharge() {
        return openCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.OPEN_CHARGE
     *
     * @param openCharge the value for T_USER_CONTRACT.OPEN_CHARGE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setOpenCharge(BigDecimal openCharge) {
        this.openCharge = openCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.CLOSE_CURR_CHARGE
     *
     * @return the value of T_USER_CONTRACT.CLOSE_CURR_CHARGE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public BigDecimal getCloseCurrCharge() {
        return closeCurrCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.CLOSE_CURR_CHARGE
     *
     * @param closeCurrCharge the value for T_USER_CONTRACT.CLOSE_CURR_CHARGE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setCloseCurrCharge(BigDecimal closeCurrCharge) {
        this.closeCurrCharge = closeCurrCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.CLOSE_LAST_CHARGE
     *
     * @return the value of T_USER_CONTRACT.CLOSE_LAST_CHARGE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public BigDecimal getCloseLastCharge() {
        return closeLastCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.CLOSE_LAST_CHARGE
     *
     * @param closeLastCharge the value for T_USER_CONTRACT.CLOSE_LAST_CHARGE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setCloseLastCharge(BigDecimal closeLastCharge) {
        this.closeLastCharge = closeLastCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.MARGIN
     *
     * @return the value of T_USER_CONTRACT.MARGIN
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public BigDecimal getMargin() {
        return margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.MARGIN
     *
     * @param margin the value for T_USER_CONTRACT.MARGIN
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setMargin(BigDecimal margin) {
        this.margin = margin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.CONTRACT_UNIT
     *
     * @return the value of T_USER_CONTRACT.CONTRACT_UNIT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Integer getContractUnit() {
        return contractUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.CONTRACT_UNIT
     *
     * @param contractUnit the value for T_USER_CONTRACT.CONTRACT_UNIT
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setContractUnit(Integer contractUnit) {
        this.contractUnit = contractUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.TICK_SIZE
     *
     * @return the value of T_USER_CONTRACT.TICK_SIZE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public BigDecimal getTickSize() {
        return tickSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.TICK_SIZE
     *
     * @param tickSize the value for T_USER_CONTRACT.TICK_SIZE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setTickSize(BigDecimal tickSize) {
        this.tickSize = tickSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.CREATE_TIME
     *
     * @return the value of T_USER_CONTRACT.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.CREATE_TIME
     *
     * @param createTime the value for T_USER_CONTRACT.CREATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.UPDATE_TIME
     *
     * @return the value of T_USER_CONTRACT.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.UPDATE_TIME
     *
     * @param updateTime the value for T_USER_CONTRACT.UPDATE_TIME
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.OPEN_CHARGE_RATE
     *
     * @return the value of T_USER_CONTRACT.OPEN_CHARGE_RATE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public BigDecimal getOpenChargeRate() {
        return openChargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.OPEN_CHARGE_RATE
     *
     * @param openChargeRate the value for T_USER_CONTRACT.OPEN_CHARGE_RATE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setOpenChargeRate(BigDecimal openChargeRate) {
        this.openChargeRate = openChargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_CONTRACT.CLOSE_CURR_CHARGE_RATE
     *
     * @return the value of T_USER_CONTRACT.CLOSE_CURR_CHARGE_RATE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public BigDecimal getCloseCurrChargeRate() {
        return closeCurrChargeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_CONTRACT.CLOSE_CURR_CHARGE_RATE
     *
     * @param closeCurrChargeRate the value for T_USER_CONTRACT.CLOSE_CURR_CHARGE_RATE
     *
     * @mbggenerated Wed Jan 18 12:54:24 CST 2017
     */
    public void setCloseCurrChargeRate(BigDecimal closeCurrChargeRate) {
        this.closeCurrChargeRate = closeCurrChargeRate;
    }

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
    
}