package com.caoxx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class FutureMarket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.INSTRUMENT_ID
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private String instrumentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.EXCHANGE_ID
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private String exchangeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.EXCHANGE_INST_ID
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private String exchangeInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.OPEN_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal openPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.CLOSE_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private String closePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.PRE_CLOSE_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal preClosePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.HIGHEST_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal highestPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.LOWEST_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal lowestPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.LAST_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal lastPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.VOLUME
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.TURNOVER
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal turnover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.BID_PRICE1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal bidPrice1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.ASK_PRICE1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal askPrice1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.BID_VOLUME1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer bidVolume1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.ASK_VOLUME1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer askVolume1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.UPPER_LIMIT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal upperLimitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.LOWER_LIMIT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal lowerLimitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.CURR_DELTA
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private String currDelta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.PRE_DELTA
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private String preDelta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.PRE_SETTLEMENT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal preSettlementPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.SETTLEMENT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private String settlementPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.OPEN_INTEREST
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal openInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.TRADING_DAY
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal tradingDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.BID_VOLUME2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer bidVolume2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.BID_PRICE2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal bidPrice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.BID_VOLUME3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer bidVolume3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.BID_PRICE3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal bidPrice3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.BID_VOLUME4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer bidVolume4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.BID_PRICE4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal bidPrice4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.BID_VOLUME5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer bidVolume5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.BID_PRICE5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal bidPrice5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.ASK_VOLUME2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer askVolume2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.ASK_PRICE2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal askPrice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.ASK_VOLUME3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer askVolume3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.ASK_PRICE3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal askPrice3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.ASK_VOLUME4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer askVolume4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.ASK_PRICE4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal askPrice4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.ASK_VOLUME5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer askVolume5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.ASK_PRICE5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private BigDecimal askPrice5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.UPDATE_TIME
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.UPDATE_MILLISEC
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Integer updateMillisec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FUTURE_MARKET.CREATE_TIME
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.INSTRUMENT_ID
     *
     * @return the value of T_FUTURE_MARKET.INSTRUMENT_ID
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public String getInstrumentId() {
        return instrumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.INSTRUMENT_ID
     *
     * @param instrumentId the value for T_FUTURE_MARKET.INSTRUMENT_ID
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setInstrumentId(String instrumentId) {
        this.instrumentId = instrumentId == null ? null : instrumentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.EXCHANGE_ID
     *
     * @return the value of T_FUTURE_MARKET.EXCHANGE_ID
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public String getExchangeId() {
        return exchangeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.EXCHANGE_ID
     *
     * @param exchangeId the value for T_FUTURE_MARKET.EXCHANGE_ID
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setExchangeId(String exchangeId) {
        this.exchangeId = exchangeId == null ? null : exchangeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.EXCHANGE_INST_ID
     *
     * @return the value of T_FUTURE_MARKET.EXCHANGE_INST_ID
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public String getExchangeInstId() {
        return exchangeInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.EXCHANGE_INST_ID
     *
     * @param exchangeInstId the value for T_FUTURE_MARKET.EXCHANGE_INST_ID
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setExchangeInstId(String exchangeInstId) {
        this.exchangeInstId = exchangeInstId == null ? null : exchangeInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.OPEN_PRICE
     *
     * @return the value of T_FUTURE_MARKET.OPEN_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getOpenPrice() {
        return openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.OPEN_PRICE
     *
     * @param openPrice the value for T_FUTURE_MARKET.OPEN_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setOpenPrice(BigDecimal openPrice) {
        this.openPrice = openPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.CLOSE_PRICE
     *
     * @return the value of T_FUTURE_MARKET.CLOSE_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public String getClosePrice() {
        return closePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.CLOSE_PRICE
     *
     * @param closePrice the value for T_FUTURE_MARKET.CLOSE_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setClosePrice(String closePrice) {
        this.closePrice = closePrice == null ? null : closePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.PRE_CLOSE_PRICE
     *
     * @return the value of T_FUTURE_MARKET.PRE_CLOSE_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getPreClosePrice() {
        return preClosePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.PRE_CLOSE_PRICE
     *
     * @param preClosePrice the value for T_FUTURE_MARKET.PRE_CLOSE_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setPreClosePrice(BigDecimal preClosePrice) {
        this.preClosePrice = preClosePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.HIGHEST_PRICE
     *
     * @return the value of T_FUTURE_MARKET.HIGHEST_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getHighestPrice() {
        return highestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.HIGHEST_PRICE
     *
     * @param highestPrice the value for T_FUTURE_MARKET.HIGHEST_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setHighestPrice(BigDecimal highestPrice) {
        this.highestPrice = highestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.LOWEST_PRICE
     *
     * @return the value of T_FUTURE_MARKET.LOWEST_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getLowestPrice() {
        return lowestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.LOWEST_PRICE
     *
     * @param lowestPrice the value for T_FUTURE_MARKET.LOWEST_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setLowestPrice(BigDecimal lowestPrice) {
        this.lowestPrice = lowestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.LAST_PRICE
     *
     * @return the value of T_FUTURE_MARKET.LAST_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getLastPrice() {
        return lastPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.LAST_PRICE
     *
     * @param lastPrice the value for T_FUTURE_MARKET.LAST_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setLastPrice(BigDecimal lastPrice) {
        this.lastPrice = lastPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.VOLUME
     *
     * @return the value of T_FUTURE_MARKET.VOLUME
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.VOLUME
     *
     * @param volume the value for T_FUTURE_MARKET.VOLUME
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setVolume(Integer volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.TURNOVER
     *
     * @return the value of T_FUTURE_MARKET.TURNOVER
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.TURNOVER
     *
     * @param turnover the value for T_FUTURE_MARKET.TURNOVER
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setTurnover(BigDecimal turnover) {
        this.turnover = turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.BID_PRICE1
     *
     * @return the value of T_FUTURE_MARKET.BID_PRICE1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getBidPrice1() {
        return bidPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.BID_PRICE1
     *
     * @param bidPrice1 the value for T_FUTURE_MARKET.BID_PRICE1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setBidPrice1(BigDecimal bidPrice1) {
        this.bidPrice1 = bidPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.ASK_PRICE1
     *
     * @return the value of T_FUTURE_MARKET.ASK_PRICE1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getAskPrice1() {
        return askPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.ASK_PRICE1
     *
     * @param askPrice1 the value for T_FUTURE_MARKET.ASK_PRICE1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setAskPrice1(BigDecimal askPrice1) {
        this.askPrice1 = askPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.BID_VOLUME1
     *
     * @return the value of T_FUTURE_MARKET.BID_VOLUME1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getBidVolume1() {
        return bidVolume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.BID_VOLUME1
     *
     * @param bidVolume1 the value for T_FUTURE_MARKET.BID_VOLUME1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setBidVolume1(Integer bidVolume1) {
        this.bidVolume1 = bidVolume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.ASK_VOLUME1
     *
     * @return the value of T_FUTURE_MARKET.ASK_VOLUME1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getAskVolume1() {
        return askVolume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.ASK_VOLUME1
     *
     * @param askVolume1 the value for T_FUTURE_MARKET.ASK_VOLUME1
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setAskVolume1(Integer askVolume1) {
        this.askVolume1 = askVolume1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.UPPER_LIMIT_PRICE
     *
     * @return the value of T_FUTURE_MARKET.UPPER_LIMIT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getUpperLimitPrice() {
        return upperLimitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.UPPER_LIMIT_PRICE
     *
     * @param upperLimitPrice the value for T_FUTURE_MARKET.UPPER_LIMIT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setUpperLimitPrice(BigDecimal upperLimitPrice) {
        this.upperLimitPrice = upperLimitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.LOWER_LIMIT_PRICE
     *
     * @return the value of T_FUTURE_MARKET.LOWER_LIMIT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getLowerLimitPrice() {
        return lowerLimitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.LOWER_LIMIT_PRICE
     *
     * @param lowerLimitPrice the value for T_FUTURE_MARKET.LOWER_LIMIT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setLowerLimitPrice(BigDecimal lowerLimitPrice) {
        this.lowerLimitPrice = lowerLimitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.CURR_DELTA
     *
     * @return the value of T_FUTURE_MARKET.CURR_DELTA
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public String getCurrDelta() {
        return currDelta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.CURR_DELTA
     *
     * @param currDelta the value for T_FUTURE_MARKET.CURR_DELTA
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setCurrDelta(String currDelta) {
        this.currDelta = currDelta == null ? null : currDelta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.PRE_DELTA
     *
     * @return the value of T_FUTURE_MARKET.PRE_DELTA
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public String getPreDelta() {
        return preDelta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.PRE_DELTA
     *
     * @param preDelta the value for T_FUTURE_MARKET.PRE_DELTA
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setPreDelta(String preDelta) {
        this.preDelta = preDelta == null ? null : preDelta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.PRE_SETTLEMENT_PRICE
     *
     * @return the value of T_FUTURE_MARKET.PRE_SETTLEMENT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getPreSettlementPrice() {
        return preSettlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.PRE_SETTLEMENT_PRICE
     *
     * @param preSettlementPrice the value for T_FUTURE_MARKET.PRE_SETTLEMENT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setPreSettlementPrice(BigDecimal preSettlementPrice) {
        this.preSettlementPrice = preSettlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.SETTLEMENT_PRICE
     *
     * @return the value of T_FUTURE_MARKET.SETTLEMENT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public String getSettlementPrice() {
        return settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.SETTLEMENT_PRICE
     *
     * @param settlementPrice the value for T_FUTURE_MARKET.SETTLEMENT_PRICE
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setSettlementPrice(String settlementPrice) {
        this.settlementPrice = settlementPrice == null ? null : settlementPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.OPEN_INTEREST
     *
     * @return the value of T_FUTURE_MARKET.OPEN_INTEREST
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getOpenInterest() {
        return openInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.OPEN_INTEREST
     *
     * @param openInterest the value for T_FUTURE_MARKET.OPEN_INTEREST
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setOpenInterest(BigDecimal openInterest) {
        this.openInterest = openInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.TRADING_DAY
     *
     * @return the value of T_FUTURE_MARKET.TRADING_DAY
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getTradingDay() {
        return tradingDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.TRADING_DAY
     *
     * @param tradingDay the value for T_FUTURE_MARKET.TRADING_DAY
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setTradingDay(BigDecimal tradingDay) {
        this.tradingDay = tradingDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.BID_VOLUME2
     *
     * @return the value of T_FUTURE_MARKET.BID_VOLUME2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getBidVolume2() {
        return bidVolume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.BID_VOLUME2
     *
     * @param bidVolume2 the value for T_FUTURE_MARKET.BID_VOLUME2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setBidVolume2(Integer bidVolume2) {
        this.bidVolume2 = bidVolume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.BID_PRICE2
     *
     * @return the value of T_FUTURE_MARKET.BID_PRICE2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getBidPrice2() {
        return bidPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.BID_PRICE2
     *
     * @param bidPrice2 the value for T_FUTURE_MARKET.BID_PRICE2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setBidPrice2(BigDecimal bidPrice2) {
        this.bidPrice2 = bidPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.BID_VOLUME3
     *
     * @return the value of T_FUTURE_MARKET.BID_VOLUME3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getBidVolume3() {
        return bidVolume3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.BID_VOLUME3
     *
     * @param bidVolume3 the value for T_FUTURE_MARKET.BID_VOLUME3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setBidVolume3(Integer bidVolume3) {
        this.bidVolume3 = bidVolume3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.BID_PRICE3
     *
     * @return the value of T_FUTURE_MARKET.BID_PRICE3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getBidPrice3() {
        return bidPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.BID_PRICE3
     *
     * @param bidPrice3 the value for T_FUTURE_MARKET.BID_PRICE3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setBidPrice3(BigDecimal bidPrice3) {
        this.bidPrice3 = bidPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.BID_VOLUME4
     *
     * @return the value of T_FUTURE_MARKET.BID_VOLUME4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getBidVolume4() {
        return bidVolume4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.BID_VOLUME4
     *
     * @param bidVolume4 the value for T_FUTURE_MARKET.BID_VOLUME4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setBidVolume4(Integer bidVolume4) {
        this.bidVolume4 = bidVolume4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.BID_PRICE4
     *
     * @return the value of T_FUTURE_MARKET.BID_PRICE4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getBidPrice4() {
        return bidPrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.BID_PRICE4
     *
     * @param bidPrice4 the value for T_FUTURE_MARKET.BID_PRICE4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setBidPrice4(BigDecimal bidPrice4) {
        this.bidPrice4 = bidPrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.BID_VOLUME5
     *
     * @return the value of T_FUTURE_MARKET.BID_VOLUME5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getBidVolume5() {
        return bidVolume5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.BID_VOLUME5
     *
     * @param bidVolume5 the value for T_FUTURE_MARKET.BID_VOLUME5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setBidVolume5(Integer bidVolume5) {
        this.bidVolume5 = bidVolume5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.BID_PRICE5
     *
     * @return the value of T_FUTURE_MARKET.BID_PRICE5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getBidPrice5() {
        return bidPrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.BID_PRICE5
     *
     * @param bidPrice5 the value for T_FUTURE_MARKET.BID_PRICE5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setBidPrice5(BigDecimal bidPrice5) {
        this.bidPrice5 = bidPrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.ASK_VOLUME2
     *
     * @return the value of T_FUTURE_MARKET.ASK_VOLUME2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getAskVolume2() {
        return askVolume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.ASK_VOLUME2
     *
     * @param askVolume2 the value for T_FUTURE_MARKET.ASK_VOLUME2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setAskVolume2(Integer askVolume2) {
        this.askVolume2 = askVolume2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.ASK_PRICE2
     *
     * @return the value of T_FUTURE_MARKET.ASK_PRICE2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getAskPrice2() {
        return askPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.ASK_PRICE2
     *
     * @param askPrice2 the value for T_FUTURE_MARKET.ASK_PRICE2
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setAskPrice2(BigDecimal askPrice2) {
        this.askPrice2 = askPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.ASK_VOLUME3
     *
     * @return the value of T_FUTURE_MARKET.ASK_VOLUME3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getAskVolume3() {
        return askVolume3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.ASK_VOLUME3
     *
     * @param askVolume3 the value for T_FUTURE_MARKET.ASK_VOLUME3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setAskVolume3(Integer askVolume3) {
        this.askVolume3 = askVolume3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.ASK_PRICE3
     *
     * @return the value of T_FUTURE_MARKET.ASK_PRICE3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getAskPrice3() {
        return askPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.ASK_PRICE3
     *
     * @param askPrice3 the value for T_FUTURE_MARKET.ASK_PRICE3
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setAskPrice3(BigDecimal askPrice3) {
        this.askPrice3 = askPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.ASK_VOLUME4
     *
     * @return the value of T_FUTURE_MARKET.ASK_VOLUME4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getAskVolume4() {
        return askVolume4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.ASK_VOLUME4
     *
     * @param askVolume4 the value for T_FUTURE_MARKET.ASK_VOLUME4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setAskVolume4(Integer askVolume4) {
        this.askVolume4 = askVolume4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.ASK_PRICE4
     *
     * @return the value of T_FUTURE_MARKET.ASK_PRICE4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getAskPrice4() {
        return askPrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.ASK_PRICE4
     *
     * @param askPrice4 the value for T_FUTURE_MARKET.ASK_PRICE4
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setAskPrice4(BigDecimal askPrice4) {
        this.askPrice4 = askPrice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.ASK_VOLUME5
     *
     * @return the value of T_FUTURE_MARKET.ASK_VOLUME5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getAskVolume5() {
        return askVolume5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.ASK_VOLUME5
     *
     * @param askVolume5 the value for T_FUTURE_MARKET.ASK_VOLUME5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setAskVolume5(Integer askVolume5) {
        this.askVolume5 = askVolume5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.ASK_PRICE5
     *
     * @return the value of T_FUTURE_MARKET.ASK_PRICE5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public BigDecimal getAskPrice5() {
        return askPrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.ASK_PRICE5
     *
     * @param askPrice5 the value for T_FUTURE_MARKET.ASK_PRICE5
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setAskPrice5(BigDecimal askPrice5) {
        this.askPrice5 = askPrice5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.UPDATE_TIME
     *
     * @return the value of T_FUTURE_MARKET.UPDATE_TIME
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.UPDATE_TIME
     *
     * @param updateTime the value for T_FUTURE_MARKET.UPDATE_TIME
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.UPDATE_MILLISEC
     *
     * @return the value of T_FUTURE_MARKET.UPDATE_MILLISEC
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Integer getUpdateMillisec() {
        return updateMillisec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.UPDATE_MILLISEC
     *
     * @param updateMillisec the value for T_FUTURE_MARKET.UPDATE_MILLISEC
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setUpdateMillisec(Integer updateMillisec) {
        this.updateMillisec = updateMillisec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FUTURE_MARKET.CREATE_TIME
     *
     * @return the value of T_FUTURE_MARKET.CREATE_TIME
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FUTURE_MARKET.CREATE_TIME
     *
     * @param createTime the value for T_FUTURE_MARKET.CREATE_TIME
     *
     * @mbggenerated Fri Jan 13 09:40:50 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}