package com.caoxx.entity;

import java.math.BigDecimal;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.BROKERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String brokerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.INVESTORID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String investorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.INSTRUMENTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String instrumentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ORDERREF
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String orderref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.USERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ORDERPRICETYPE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String orderpricetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.DIRECTION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.COMBOFFSETFLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String comboffsetflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.COMBHEDGEFLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String combhedgeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.LIMITPRICE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private BigDecimal limitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.VOLUMETOTALORIGINAL
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long volumetotaloriginal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.TIMECONDITION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String timecondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.GTDDATE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String gtddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.VOLUMECONDITION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String volumecondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.MINVOLUME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long minvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.CONTINGENTCONDITION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String contingentcondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.STOPPRICE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private BigDecimal stopprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.FORCECLOSEREASON
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String forceclosereason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ISAUTOSUSPEND
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long isautosuspend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.BUSINESSUNIT
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String businessunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.REQUESTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long requestid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ORDERLOCALID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String orderlocalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.EXCHANGEID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String exchangeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.PARTICIPANTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String participantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.CLIENTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String clientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.EXCHANGEINSTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String exchangeinstid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.TRADERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String traderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.INSTALLID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long installid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ORDERSUBMITSTATUS
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String ordersubmitstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.NOTIFYSEQUENCE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long notifysequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.TRADINGDAY
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String tradingday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.SETTLEMENTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long settlementid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ORDERSYSID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String ordersysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ORDERSOURCE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String ordersource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ORDERSTATUS
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ORDERTYPE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.VOLUMETRADED
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long volumetraded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.VOLUMETOTAL
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long volumetotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.INSERTDATE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String insertdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.INSERTTIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String inserttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ACTIVETIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String activetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.SUSPENDTIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String suspendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.UPDATETIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.CANCELTIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String canceltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ACTIVETRADERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String activetraderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.CLEARINGPARTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String clearingpartid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.SEQUENCENO
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long sequenceno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.FRONTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private BigDecimal frontid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.SESSIONID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private BigDecimal sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.USERPRODUCTINFO
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String userproductinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.STATUSMSG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String statusmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.USERFORCECLOSE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long userforceclose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ACTIVEUSERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String activeuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.BROKERORDERSEQ
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long brokerorderseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.RELATIVEORDERSYSID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private String relativeordersysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ZCETOTALTRADEDVOLUME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long zcetotaltradedvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.ISSWAPORDER
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    private Long isswaporder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.SUBUSERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.BROKERID
     *
     * @return the value of T_ORDER.BROKERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getBrokerid() {
        return brokerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.BROKERID
     *
     * @param brokerid the value for T_ORDER.BROKERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setBrokerid(String brokerid) {
        this.brokerid = brokerid == null ? null : brokerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.INVESTORID
     *
     * @return the value of T_ORDER.INVESTORID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getInvestorid() {
        return investorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.INVESTORID
     *
     * @param investorid the value for T_ORDER.INVESTORID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setInvestorid(String investorid) {
        this.investorid = investorid == null ? null : investorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.INSTRUMENTID
     *
     * @return the value of T_ORDER.INSTRUMENTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getInstrumentid() {
        return instrumentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.INSTRUMENTID
     *
     * @param instrumentid the value for T_ORDER.INSTRUMENTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setInstrumentid(String instrumentid) {
        this.instrumentid = instrumentid == null ? null : instrumentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ORDERREF
     *
     * @return the value of T_ORDER.ORDERREF
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getOrderref() {
        return orderref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ORDERREF
     *
     * @param orderref the value for T_ORDER.ORDERREF
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setOrderref(String orderref) {
        this.orderref = orderref == null ? null : orderref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.USERID
     *
     * @return the value of T_ORDER.USERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.USERID
     *
     * @param userid the value for T_ORDER.USERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ORDERPRICETYPE
     *
     * @return the value of T_ORDER.ORDERPRICETYPE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getOrderpricetype() {
        return orderpricetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ORDERPRICETYPE
     *
     * @param orderpricetype the value for T_ORDER.ORDERPRICETYPE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setOrderpricetype(String orderpricetype) {
        this.orderpricetype = orderpricetype == null ? null : orderpricetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.DIRECTION
     *
     * @return the value of T_ORDER.DIRECTION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.DIRECTION
     *
     * @param direction the value for T_ORDER.DIRECTION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.COMBOFFSETFLAG
     *
     * @return the value of T_ORDER.COMBOFFSETFLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getComboffsetflag() {
        return comboffsetflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.COMBOFFSETFLAG
     *
     * @param comboffsetflag the value for T_ORDER.COMBOFFSETFLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setComboffsetflag(String comboffsetflag) {
        this.comboffsetflag = comboffsetflag == null ? null : comboffsetflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.COMBHEDGEFLAG
     *
     * @return the value of T_ORDER.COMBHEDGEFLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getCombhedgeflag() {
        return combhedgeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.COMBHEDGEFLAG
     *
     * @param combhedgeflag the value for T_ORDER.COMBHEDGEFLAG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setCombhedgeflag(String combhedgeflag) {
        this.combhedgeflag = combhedgeflag == null ? null : combhedgeflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.LIMITPRICE
     *
     * @return the value of T_ORDER.LIMITPRICE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public BigDecimal getLimitprice() {
        return limitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.LIMITPRICE
     *
     * @param limitprice the value for T_ORDER.LIMITPRICE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setLimitprice(BigDecimal limitprice) {
        this.limitprice = limitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.VOLUMETOTALORIGINAL
     *
     * @return the value of T_ORDER.VOLUMETOTALORIGINAL
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getVolumetotaloriginal() {
        return volumetotaloriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.VOLUMETOTALORIGINAL
     *
     * @param volumetotaloriginal the value for T_ORDER.VOLUMETOTALORIGINAL
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setVolumetotaloriginal(Long volumetotaloriginal) {
        this.volumetotaloriginal = volumetotaloriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.TIMECONDITION
     *
     * @return the value of T_ORDER.TIMECONDITION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getTimecondition() {
        return timecondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.TIMECONDITION
     *
     * @param timecondition the value for T_ORDER.TIMECONDITION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setTimecondition(String timecondition) {
        this.timecondition = timecondition == null ? null : timecondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.GTDDATE
     *
     * @return the value of T_ORDER.GTDDATE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getGtddate() {
        return gtddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.GTDDATE
     *
     * @param gtddate the value for T_ORDER.GTDDATE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setGtddate(String gtddate) {
        this.gtddate = gtddate == null ? null : gtddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.VOLUMECONDITION
     *
     * @return the value of T_ORDER.VOLUMECONDITION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getVolumecondition() {
        return volumecondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.VOLUMECONDITION
     *
     * @param volumecondition the value for T_ORDER.VOLUMECONDITION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setVolumecondition(String volumecondition) {
        this.volumecondition = volumecondition == null ? null : volumecondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.MINVOLUME
     *
     * @return the value of T_ORDER.MINVOLUME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getMinvolume() {
        return minvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.MINVOLUME
     *
     * @param minvolume the value for T_ORDER.MINVOLUME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setMinvolume(Long minvolume) {
        this.minvolume = minvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.CONTINGENTCONDITION
     *
     * @return the value of T_ORDER.CONTINGENTCONDITION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getContingentcondition() {
        return contingentcondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.CONTINGENTCONDITION
     *
     * @param contingentcondition the value for T_ORDER.CONTINGENTCONDITION
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setContingentcondition(String contingentcondition) {
        this.contingentcondition = contingentcondition == null ? null : contingentcondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.STOPPRICE
     *
     * @return the value of T_ORDER.STOPPRICE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public BigDecimal getStopprice() {
        return stopprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.STOPPRICE
     *
     * @param stopprice the value for T_ORDER.STOPPRICE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setStopprice(BigDecimal stopprice) {
        this.stopprice = stopprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.FORCECLOSEREASON
     *
     * @return the value of T_ORDER.FORCECLOSEREASON
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getForceclosereason() {
        return forceclosereason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.FORCECLOSEREASON
     *
     * @param forceclosereason the value for T_ORDER.FORCECLOSEREASON
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setForceclosereason(String forceclosereason) {
        this.forceclosereason = forceclosereason == null ? null : forceclosereason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ISAUTOSUSPEND
     *
     * @return the value of T_ORDER.ISAUTOSUSPEND
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getIsautosuspend() {
        return isautosuspend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ISAUTOSUSPEND
     *
     * @param isautosuspend the value for T_ORDER.ISAUTOSUSPEND
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setIsautosuspend(Long isautosuspend) {
        this.isautosuspend = isautosuspend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.BUSINESSUNIT
     *
     * @return the value of T_ORDER.BUSINESSUNIT
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getBusinessunit() {
        return businessunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.BUSINESSUNIT
     *
     * @param businessunit the value for T_ORDER.BUSINESSUNIT
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setBusinessunit(String businessunit) {
        this.businessunit = businessunit == null ? null : businessunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.REQUESTID
     *
     * @return the value of T_ORDER.REQUESTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getRequestid() {
        return requestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.REQUESTID
     *
     * @param requestid the value for T_ORDER.REQUESTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setRequestid(Long requestid) {
        this.requestid = requestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ORDERLOCALID
     *
     * @return the value of T_ORDER.ORDERLOCALID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getOrderlocalid() {
        return orderlocalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ORDERLOCALID
     *
     * @param orderlocalid the value for T_ORDER.ORDERLOCALID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setOrderlocalid(String orderlocalid) {
        this.orderlocalid = orderlocalid == null ? null : orderlocalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.EXCHANGEID
     *
     * @return the value of T_ORDER.EXCHANGEID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getExchangeid() {
        return exchangeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.EXCHANGEID
     *
     * @param exchangeid the value for T_ORDER.EXCHANGEID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setExchangeid(String exchangeid) {
        this.exchangeid = exchangeid == null ? null : exchangeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.PARTICIPANTID
     *
     * @return the value of T_ORDER.PARTICIPANTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getParticipantid() {
        return participantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.PARTICIPANTID
     *
     * @param participantid the value for T_ORDER.PARTICIPANTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setParticipantid(String participantid) {
        this.participantid = participantid == null ? null : participantid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.CLIENTID
     *
     * @return the value of T_ORDER.CLIENTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.CLIENTID
     *
     * @param clientid the value for T_ORDER.CLIENTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setClientid(String clientid) {
        this.clientid = clientid == null ? null : clientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.EXCHANGEINSTID
     *
     * @return the value of T_ORDER.EXCHANGEINSTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getExchangeinstid() {
        return exchangeinstid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.EXCHANGEINSTID
     *
     * @param exchangeinstid the value for T_ORDER.EXCHANGEINSTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setExchangeinstid(String exchangeinstid) {
        this.exchangeinstid = exchangeinstid == null ? null : exchangeinstid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.TRADERID
     *
     * @return the value of T_ORDER.TRADERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getTraderid() {
        return traderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.TRADERID
     *
     * @param traderid the value for T_ORDER.TRADERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setTraderid(String traderid) {
        this.traderid = traderid == null ? null : traderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.INSTALLID
     *
     * @return the value of T_ORDER.INSTALLID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getInstallid() {
        return installid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.INSTALLID
     *
     * @param installid the value for T_ORDER.INSTALLID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setInstallid(Long installid) {
        this.installid = installid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ORDERSUBMITSTATUS
     *
     * @return the value of T_ORDER.ORDERSUBMITSTATUS
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getOrdersubmitstatus() {
        return ordersubmitstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ORDERSUBMITSTATUS
     *
     * @param ordersubmitstatus the value for T_ORDER.ORDERSUBMITSTATUS
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setOrdersubmitstatus(String ordersubmitstatus) {
        this.ordersubmitstatus = ordersubmitstatus == null ? null : ordersubmitstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.NOTIFYSEQUENCE
     *
     * @return the value of T_ORDER.NOTIFYSEQUENCE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getNotifysequence() {
        return notifysequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.NOTIFYSEQUENCE
     *
     * @param notifysequence the value for T_ORDER.NOTIFYSEQUENCE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setNotifysequence(Long notifysequence) {
        this.notifysequence = notifysequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.TRADINGDAY
     *
     * @return the value of T_ORDER.TRADINGDAY
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getTradingday() {
        return tradingday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.TRADINGDAY
     *
     * @param tradingday the value for T_ORDER.TRADINGDAY
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setTradingday(String tradingday) {
        this.tradingday = tradingday == null ? null : tradingday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.SETTLEMENTID
     *
     * @return the value of T_ORDER.SETTLEMENTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getSettlementid() {
        return settlementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.SETTLEMENTID
     *
     * @param settlementid the value for T_ORDER.SETTLEMENTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setSettlementid(Long settlementid) {
        this.settlementid = settlementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ORDERSYSID
     *
     * @return the value of T_ORDER.ORDERSYSID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getOrdersysid() {
        return ordersysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ORDERSYSID
     *
     * @param ordersysid the value for T_ORDER.ORDERSYSID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setOrdersysid(String ordersysid) {
        this.ordersysid = ordersysid == null ? null : ordersysid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ORDERSOURCE
     *
     * @return the value of T_ORDER.ORDERSOURCE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getOrdersource() {
        return ordersource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ORDERSOURCE
     *
     * @param ordersource the value for T_ORDER.ORDERSOURCE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setOrdersource(String ordersource) {
        this.ordersource = ordersource == null ? null : ordersource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ORDERSTATUS
     *
     * @return the value of T_ORDER.ORDERSTATUS
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ORDERSTATUS
     *
     * @param orderstatus the value for T_ORDER.ORDERSTATUS
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus == null ? null : orderstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ORDERTYPE
     *
     * @return the value of T_ORDER.ORDERTYPE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ORDERTYPE
     *
     * @param ordertype the value for T_ORDER.ORDERTYPE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype == null ? null : ordertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.VOLUMETRADED
     *
     * @return the value of T_ORDER.VOLUMETRADED
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getVolumetraded() {
        return volumetraded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.VOLUMETRADED
     *
     * @param volumetraded the value for T_ORDER.VOLUMETRADED
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setVolumetraded(Long volumetraded) {
        this.volumetraded = volumetraded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.VOLUMETOTAL
     *
     * @return the value of T_ORDER.VOLUMETOTAL
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getVolumetotal() {
        return volumetotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.VOLUMETOTAL
     *
     * @param volumetotal the value for T_ORDER.VOLUMETOTAL
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setVolumetotal(Long volumetotal) {
        this.volumetotal = volumetotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.INSERTDATE
     *
     * @return the value of T_ORDER.INSERTDATE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getInsertdate() {
        return insertdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.INSERTDATE
     *
     * @param insertdate the value for T_ORDER.INSERTDATE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setInsertdate(String insertdate) {
        this.insertdate = insertdate == null ? null : insertdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.INSERTTIME
     *
     * @return the value of T_ORDER.INSERTTIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.INSERTTIME
     *
     * @param inserttime the value for T_ORDER.INSERTTIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setInserttime(String inserttime) {
        this.inserttime = inserttime == null ? null : inserttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ACTIVETIME
     *
     * @return the value of T_ORDER.ACTIVETIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getActivetime() {
        return activetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ACTIVETIME
     *
     * @param activetime the value for T_ORDER.ACTIVETIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setActivetime(String activetime) {
        this.activetime = activetime == null ? null : activetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.SUSPENDTIME
     *
     * @return the value of T_ORDER.SUSPENDTIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getSuspendtime() {
        return suspendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.SUSPENDTIME
     *
     * @param suspendtime the value for T_ORDER.SUSPENDTIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setSuspendtime(String suspendtime) {
        this.suspendtime = suspendtime == null ? null : suspendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.UPDATETIME
     *
     * @return the value of T_ORDER.UPDATETIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.UPDATETIME
     *
     * @param updatetime the value for T_ORDER.UPDATETIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.CANCELTIME
     *
     * @return the value of T_ORDER.CANCELTIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getCanceltime() {
        return canceltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.CANCELTIME
     *
     * @param canceltime the value for T_ORDER.CANCELTIME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setCanceltime(String canceltime) {
        this.canceltime = canceltime == null ? null : canceltime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ACTIVETRADERID
     *
     * @return the value of T_ORDER.ACTIVETRADERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getActivetraderid() {
        return activetraderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ACTIVETRADERID
     *
     * @param activetraderid the value for T_ORDER.ACTIVETRADERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setActivetraderid(String activetraderid) {
        this.activetraderid = activetraderid == null ? null : activetraderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.CLEARINGPARTID
     *
     * @return the value of T_ORDER.CLEARINGPARTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getClearingpartid() {
        return clearingpartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.CLEARINGPARTID
     *
     * @param clearingpartid the value for T_ORDER.CLEARINGPARTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setClearingpartid(String clearingpartid) {
        this.clearingpartid = clearingpartid == null ? null : clearingpartid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.SEQUENCENO
     *
     * @return the value of T_ORDER.SEQUENCENO
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getSequenceno() {
        return sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.SEQUENCENO
     *
     * @param sequenceno the value for T_ORDER.SEQUENCENO
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setSequenceno(Long sequenceno) {
        this.sequenceno = sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.FRONTID
     *
     * @return the value of T_ORDER.FRONTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public BigDecimal getFrontid() {
        return frontid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.FRONTID
     *
     * @param frontid the value for T_ORDER.FRONTID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setFrontid(BigDecimal frontid) {
        this.frontid = frontid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.SESSIONID
     *
     * @return the value of T_ORDER.SESSIONID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public BigDecimal getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.SESSIONID
     *
     * @param sessionid the value for T_ORDER.SESSIONID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setSessionid(BigDecimal sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.USERPRODUCTINFO
     *
     * @return the value of T_ORDER.USERPRODUCTINFO
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getUserproductinfo() {
        return userproductinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.USERPRODUCTINFO
     *
     * @param userproductinfo the value for T_ORDER.USERPRODUCTINFO
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setUserproductinfo(String userproductinfo) {
        this.userproductinfo = userproductinfo == null ? null : userproductinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.STATUSMSG
     *
     * @return the value of T_ORDER.STATUSMSG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getStatusmsg() {
        return statusmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.STATUSMSG
     *
     * @param statusmsg the value for T_ORDER.STATUSMSG
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setStatusmsg(String statusmsg) {
        this.statusmsg = statusmsg == null ? null : statusmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.USERFORCECLOSE
     *
     * @return the value of T_ORDER.USERFORCECLOSE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getUserforceclose() {
        return userforceclose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.USERFORCECLOSE
     *
     * @param userforceclose the value for T_ORDER.USERFORCECLOSE
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setUserforceclose(Long userforceclose) {
        this.userforceclose = userforceclose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ACTIVEUSERID
     *
     * @return the value of T_ORDER.ACTIVEUSERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getActiveuserid() {
        return activeuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ACTIVEUSERID
     *
     * @param activeuserid the value for T_ORDER.ACTIVEUSERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setActiveuserid(String activeuserid) {
        this.activeuserid = activeuserid == null ? null : activeuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.BROKERORDERSEQ
     *
     * @return the value of T_ORDER.BROKERORDERSEQ
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getBrokerorderseq() {
        return brokerorderseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.BROKERORDERSEQ
     *
     * @param brokerorderseq the value for T_ORDER.BROKERORDERSEQ
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setBrokerorderseq(Long brokerorderseq) {
        this.brokerorderseq = brokerorderseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.RELATIVEORDERSYSID
     *
     * @return the value of T_ORDER.RELATIVEORDERSYSID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public String getRelativeordersysid() {
        return relativeordersysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.RELATIVEORDERSYSID
     *
     * @param relativeordersysid the value for T_ORDER.RELATIVEORDERSYSID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setRelativeordersysid(String relativeordersysid) {
        this.relativeordersysid = relativeordersysid == null ? null : relativeordersysid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ZCETOTALTRADEDVOLUME
     *
     * @return the value of T_ORDER.ZCETOTALTRADEDVOLUME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getZcetotaltradedvolume() {
        return zcetotaltradedvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ZCETOTALTRADEDVOLUME
     *
     * @param zcetotaltradedvolume the value for T_ORDER.ZCETOTALTRADEDVOLUME
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setZcetotaltradedvolume(Long zcetotaltradedvolume) {
        this.zcetotaltradedvolume = zcetotaltradedvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.ISSWAPORDER
     *
     * @return the value of T_ORDER.ISSWAPORDER
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public Long getIsswaporder() {
        return isswaporder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.ISSWAPORDER
     *
     * @param isswaporder the value for T_ORDER.ISSWAPORDER
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    public void setIsswaporder(Long isswaporder) {
        this.isswaporder = isswaporder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.SUBUSERID
     *
     * @return the value of T_ORDER.SUBUSERID
     *
     * @mbggenerated Wed Feb 15 10:09:24 CST 2017
     */
    
}