package com.caoxx.dao;

public class PositionsDetail2 {
	
	

	private String instrumentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_POSITIONS_DETAIL.DIRECTION
     *
     * @mbggenerated Sun Jun 04 12:42:18 CST 2017
     */
    private String direction;
    
    private double openPrice;

    public double getOpenPrice() {
		return openPrice;
	}

	public void setOpenPrice(double openPrice) {
		this.openPrice = openPrice;
	}

	public String getInstrumentid() {
		return instrumentid;
	}

	public void setInstrumentid(String instrumentid) {
		this.instrumentid = instrumentid;
	}

	public String getDirection() {
		return direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	public Long getVolume() {
		return volume;
	}

	public void setVolume(Long volume) {
		this.volume = volume;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_POSITIONS_DETAIL.VOLUME
     *
     * @mbggenerated Sun Jun 04 12:42:18 CST 2017
     */
    private Long volume;

    
}